# PayPilot blog — 100 posts: (topic, slug, working title, angle). All live at /blog/<slug>/
P = [
# --- Send & receive money (25)
("money","how-instant-money-transfers-work","How Instant Money Transfers Actually Work","ledger moves inside a network vs bank rails; why some are instant and some aren't"),
("money","splitting-bills-with-friends","The Painless Guide to Splitting Bills With Friends","even vs itemized splits, requests, reminders, etiquette"),
("money","paying-your-roommates-rent-share","Paying Your Share of Rent Through an App","recurring requests, records, landlord vs roommate payments"),
("money","sending-money-to-family","Sending Money to Family Without the Hassle","speed, confirmation, safety checks before sending"),
("money","request-money-etiquette","Request-Money Etiquette: How to Ask Without Awkwardness","timing, notes, reminders"),
("money","p2p-payment-scams","Peer-to-Peer Payment Scams and How to Spot Them","fake buyer overpayment, impersonation, 'accidental' sends; payments may not be reversible"),
("money","p2p-for-small-business","Should Your Small Business Accept Peer-to-Peer Payments?","personal vs business accounts, records, protections"),
("money","qr-code-wallet-payments","Paying and Getting Paid With a Wallet QR Code","how QR wallet payments work at stalls and between friends"),
("money","wallet-balance-vs-bank-transfer","Wallet Balance vs. Paying Straight From Your Bank","holding a balance, funding sources, transfer timing"),
("money","cashing-out-a-wallet-balance","Moving Money From Your Wallet to Your Bank","standard vs instant transfer, timing, fees disclosed in app"),
("money","paying-the-babysitter-digitally","Paying Babysitters, Tutors and Dog Walkers Digitally","household help, records, tips"),
("money","group-trip-expenses","Managing Group Trip Expenses Without a Spreadsheet","shared costs, settling up at the end"),
("money","gifting-money-digitally","Gifting Money Digitally: Birthdays, Weddings and Holidays","notes, timing, privacy"),
("money","fundraising-with-friends","Collecting Money for a Group Gift or Team Fund","organizer tips, transparency"),
("money","side-hustle-getting-paid","Getting Paid for Your Side Hustle","invoices vs requests vs links; keeping income records (consult a tax pro)"),
("money","freelancer-payment-options","Payment Options Every Freelancer Should Offer","cards, links, transfers, deposits"),
("money","p2p-payment-privacy","Privacy Settings on Payment Apps: What to Check","public vs private activity, contacts"),
("money","sent-money-to-wrong-person","Sent Money to the Wrong Person? What to Do Next","act quickly, contact support, prevention"),
("money","p2p-limits-and-verification","Why Payment Apps Have Limits and Identity Checks","verification, fraud prevention, regulations in general terms"),
("money","teaching-teens-digital-money","Teaching Teens to Handle Digital Money","allowance, spending awareness, safety"),
("money","contactless-wallet-vs-card","Phone Wallet or Physical Card: Which Should You Tap?","tokenization, convenience, backup"),
("money","digital-tips-for-service-workers","How Digital Tipping Works for Service Workers","tip prompts, QR tips, payouts"),
("money","paying-at-farmers-markets","Paying (and Getting Paid) at Farmers Markets","vendors, QR, readers, connectivity"),
("money","p2p-vs-card-payment-for-sellers","Getting Paid by Friends vs. Getting Paid by Customers","why business payments need different tools"),
("money","future-of-sending-money","Where Sending Money Is Headed Next","real-time rails, request-to-pay, wallets (no stats)"),
# --- Card acceptance (20)
("cards","first-week-accepting-cards","Your First Week Accepting Cards: A Day-by-Day Plan","setup, test transactions, staff training"),
("cards","what-happens-when-a-card-is-declined","What Really Happens When a Card Is Declined","decline reasons, what to say to customers"),
("cards","tap-to-pay-on-iphone-and-android","Accepting Tap to Pay on a Phone","phone as terminal, use cases, limits"),
("cards","card-on-file-for-repeat-customers","Card on File: Faster Checkout for Regulars","consent, storage via tokens, no-show fees"),
("cards","pre-authorization-holds-explained","Pre-Authorization Holds, Explained Simply","bars, hotels, rentals; releasing holds"),
("cards","manual-card-entry-risks","When (and Why Not) to Key In a Card Number","card-not-present risk, safeguards"),
("cards","processing-fees-on-small-sales","Why a $3 Sale Can Cost More to Process","fixed per-transaction costs math"),
("cards","tips-and-card-processing","How Tips Flow Through Card Payments","adjustments, batch timing, payouts"),
("cards","card-acceptance-at-pop-up-events","Taking Cards at a Pop-Up Event","offline mode, battery, signage"),
("cards","accepting-cards-for-services-at-home","Taking Card Payments on House Calls","mobile readers, invoices, deposits"),
("cards","daily-batch-close-routine","The End-of-Day Batch Close Routine","why closing batches matters, checklist"),
("cards","refund-policies-that-reduce-disputes","Writing a Refund Policy That Prevents Disputes","clarity, display, consistency"),
("cards","choosing-a-card-reader","How to Choose a Card Reader for a Small Business","countertop vs mobile vs handheld"),
("cards","card-brands-and-acceptance-marks","Card Brands, Networks and Acceptance Marks","what the logos mean, signage"),
("cards","signature-and-pin-today","Do Customers Still Need to Sign or Enter a PIN?","CVM basics, when PIN appears"),
("cards","handling-a-suspicious-transaction","What to Do When a Transaction Feels Suspicious","red flags, calling for authorization, staff scripts"),
("cards","processing-statement-basics-for-new-owners","Reading Your First Processing Statement","deposits vs sales vs fees"),
("cards","deposits-timing-explained","When Will My Card Sales Hit My Bank?","batch cutoff, weekends, holidays"),
("cards","cash-discount-signage-guide","Posting Dual Prices: Signage and Receipt Basics","disclosure, rules vary by state/network"),
("cards","why-switching-payment-providers-is-easier-now","Switching Payment Providers Is Easier Than You Think","checklist, reprogramming terminals"),
# --- Point of sale (20)
("pos","what-a-modern-pos-does","What a Modern POS Does Beyond Ringing Sales","inventory, staff, reports, loyalty"),
("pos","pos-for-restaurants-front-and-back","Restaurant POS: Front of House to Kitchen","tickets, coursing, KDS, handhelds"),
("pos","pos-for-retail-boutiques","POS Setup for a Retail Boutique","variants, barcodes, returns"),
("pos","pos-for-salons","POS for Salons and Barbershops","appointments, tips, product sales"),
("pos","pos-for-coffee-shops","Building a Fast Coffee Shop Checkout","modifiers, speed, loyalty"),
("pos","pos-for-food-trucks","Food Truck POS: Built for the Window","menus, lines, offline"),
("pos","menu-engineering-with-pos-data","Menu Engineering With Your POS Data","stars, plowhorses, puzzles, dogs"),
("pos","inventory-counts-made-simple","Inventory Counts Without Closing the Store","cycle counts, variances"),
("pos","employee-permissions-pos","Setting Employee Permissions on a POS","roles, voids, discounts"),
("pos","tip-pooling-done-right","Tip Pooling Done Right","methods, transparency, check local labor law"),
("pos","handhelds-tableside-ordering","Why Tableside Handhelds Speed Up Service","turn times, accuracy"),
("pos","kitchen-display-systems","Kitchen Display Systems vs. Paper Tickets","timers, routing"),
("pos","online-ordering-from-your-pos","Running Online Orders Through Your POS","one menu, one inventory"),
("pos","loyalty-programs-that-work","Loyalty Programs Customers Actually Use","points vs visits vs perks"),
("pos","gift-cards-for-small-business","Selling Gift Cards: A Small Business Playbook","digital vs physical, breakage basics"),
("pos","pos-reports-to-check-weekly","The Five POS Reports to Check Every Week","sales, labor, items, discounts, refunds"),
("pos","multi-location-pos","Running Multiple Locations From One POS","central menus, transfers"),
("pos","pos-hardware-checklist","The Complete POS Hardware Checklist","terminal, printer, drawer, scanner"),
("pos","pos-offline-mode","What Happens to Your POS When the Wi-Fi Drops","offline mode, risks, syncing"),
("pos","choosing-pos-software","How to Choose POS Software: 12 Questions","fit, contracts, support"),
# --- Online payments (15)
("online","launching-online-checkout","Launching Online Checkout in an Afternoon","hosted checkout steps"),
("online","payment-links-for-instagram-sellers","Selling on Instagram With Payment Links","DM checkout flow"),
("online","invoices-that-get-paid-faster","Invoices That Get Paid Faster","pay buttons, due dates, reminders"),
("online","subscription-box-billing","Billing a Subscription Box Business","cycles, failed payments, pausing"),
("online","checkout-abandonment-fixes","Why Shoppers Abandon Checkout and How to Fix It","steps, wallets, trust"),
("online","digital-wallets-at-checkout","Adding Digital Wallets to Your Checkout","one-tap buttons"),
("online","accepting-payments-on-a-website-without-code","Taking Payments on Your Website Without Writing Code","embeds, links"),
("online","payments-api-basics","Payments API Basics for Non-Developers","tokens, webhooks, test mode"),
("online","webhooks-explained","Webhooks Explained for Business Owners","event notifications"),
("online","recurring-donations","Setting Up Recurring Donations","nonprofits, donor experience"),
("online","deposits-for-bookings","Taking Deposits for Bookings and Reservations","partial payments, cancellation policy"),
("online","selling-digital-products","Getting Paid for Digital Products","delivery, refunds"),
("online","event-ticket-payments","Selling Event Tickets Online","capacity, refunds, door sales"),
("online","b2b-online-invoicing","Invoicing Business Clients Online","net terms, ACH vs card"),
("online","international-online-customers","Selling to Customers Outside the U.S.","currency, fraud checks, fees"),
# --- Security & trust (10)
("security","tokenization-for-business-owners","Tokenization in Plain English","why stored tokens beat stored numbers"),
("security","protecting-your-payments-account","Locking Down Your Payments Account","2FA, roles, alerts"),
("security","phishing-attacks-on-merchants","Phishing Attacks That Target Merchants","fake processor emails, verification"),
("security","fraud-signs-online-orders","Warning Signs of a Fraudulent Online Order","mismatches, rush shipping"),
("security","card-skimming-prevention","Protecting Your Terminals From Skimming","inspections, tamper seals"),
("security","data-you-should-never-store","Customer Data You Should Never Store","full card numbers, CVV"),
("security","secure-wifi-for-payments","Wi-Fi Security for Your Payment Devices","separate networks"),
("security","handling-disputes-calmly","Handling a Payment Dispute Step by Step","evidence, deadlines"),
("security","account-takeover-protection-for-wallet-users","Keeping Your Wallet Safe From Account Takeover","SIM swap, passcodes"),
("security","what-encryption-means-at-checkout","What 'Encrypted' Really Means at Checkout","in transit vs at rest"),
# --- Growth (10)
("growth","raising-average-ticket","Seven Ways to Raise Your Average Ticket","upsells at POS"),
("growth","using-sales-data-to-staff","Scheduling Staff With Your Sales Data","peak hours"),
("growth","turning-receipts-into-marketing","Turning Digital Receipts Into Marketing","offers, reviews"),
("growth","customer-directory-crm","Building a Customer Directory From Your Payments","consent, segments"),
("growth","seasonal-promotions-pos","Running Seasonal Promotions at the Register","discount setup"),
("growth","pricing-in-a-cashless-world","Pricing Your Products When Most Customers Tap","psychological pricing, dual pricing note"),
("growth","opening-day-checklist","The Payments Side of an Opening-Day Checklist","test everything"),
("growth","cash-flow-from-faster-deposits","How Faster Deposits Change Your Cash Flow","planning around next-day funding"),
("growth","working-capital-for-pos-merchants","When a Growing Merchant Needs Working Capital","funding options via partners like Fidelity Funding"),
("growth","reviews-and-reputation-at-checkout","Asking for Reviews at Checkout","timing, QR"),
]
if __name__ == "__main__":
    import json, collections
    print(len(P), collections.Counter(p[0] for p in P))
    assert len({p[1] for p in P}) == len(P)
    json.dump([{"topic": t, "slug": s, "title": ti, "angle": a, "url": f"/blog/{s}/"} for t, s, ti, a in P], open("content/manifest.json", "w"), indent=0)
